---
title: "Grad Non-Grad Pre-Trend Tests"
author: "Sarah Giordano"
date: "2026-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(fixest)
library(survival)
library(broom)
library(car)


root <- "C://Users/sarah/Documents/CMU/Spring 2026/Systems Synthesis/"
data_dir <- paste0(root,"Data/Matched/")
output_dir <- paste0(root, "Output/")
```



```{r cars}
#Load data files

matched_wide <- read_csv(paste0(data_dir, "matched-within-cohort-grad-non-grad.csv"))
matched_panel <-read_csv(paste0(data_dir, "matched-panel-grad-non-grad.csv"))

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
#add relative year time to panel data

matched_panel <- matched_panel %>%
  mutate(
    rel_year = as.integer(year-end_year)
  )

matched_panel <- matched_panel %>%
  filter(rel_year %in% c(0,1,2,3,-1,-2,-3))

#split panel data into the pre/post cohort
matched_panel_pre22  <- matched_panel %>% filter(cohort_2022 == 0, rel_year %in% c(0,1,2,3,-1,-2,-3))
matched_panel_post22 <- matched_panel %>% filter(cohort_2022 == 1, rel_year %in% c(0,1,2,3,-1,-2,-3))

#Event study regressions for full TIP participant pool

employed_f  <- feols(employed_full_year ~ i(rel_year, treatment, ref = -1) | tip_id + year,
                     cluster = ~tip_id, data = matched_panel)

employed_p  <- feols(employed_partial_year ~ i(rel_year, treatment, ref = -1) | tip_id + year,
                     cluster = ~tip_id, data = matched_panel)

earn  <- feols(log(earnings_full_year+1) ~ i(rel_year, treatment, ref = -1) | tip_id + year,
                     cluster = ~tip_id, data = matched_panel)

offense  <- feols(offended_year ~ i(rel_year, treatment, ref = -1) | tip_id + year,
                     cluster = ~tip_id, data = matched_panel)

#Event study regressions for pre-2022 cohort

employed_f_pre22  <- feols(employed_full_year ~ i(rel_year, treatment, ref = -1) | tip_id + year,
                     cluster = ~tip_id, data = matched_panel_pre22)

employed_p_pre22  <- feols(employed_partial_year ~ i(rel_year, treatment, ref = -1) | tip_id + year,
                     cluster = ~tip_id, data = matched_panel_pre22)

earn_pre22  <- feols(log(earnings_full_year+1) ~ i(rel_year, treatment, ref = -1) | tip_id + year,
                     cluster = ~tip_id, data = matched_panel_pre22)

offense_pre22  <- feols(offended_year ~ i(rel_year, treatment, ref = -1) | tip_id + year,
                     cluster = ~tip_id, data = matched_panel_pre22)

#Event study regression for post-2022 cohort

employed_f_post22  <- feols(employed_full_year ~ i(rel_year, treatment, ref = -1) | tip_id + year,
                     cluster = ~tip_id, data = matched_panel_post22)

employed_p_post22  <- feols(employed_partial_year ~ i(rel_year, treatment, ref = -1) | tip_id + year,
                     cluster = ~tip_id, data = matched_panel_post22)

earn_post22  <- feols(log(earnings_full_year+1) ~ i(rel_year, treatment, ref = -1) | tip_id + year,
                     cluster = ~tip_id, data = matched_panel_post22)

offense_post22  <- feols(offended_year ~ i(rel_year, treatment, ref = -1) | tip_id + year,
                     cluster = ~tip_id, data = matched_panel_post22)

```


```{r}
pretrend_test <- function(model, label) {
  cn  <- names(coef(model))
  pre <- grep("rel_year::-(2|3)", cn, value = TRUE)
  if (length(pre) == 0) {
    cat(label, ": no pre-period terms\n")
    return(invisible(NULL))
  }
  test   <- linearHypothesis(model, paste(pre, "= 0"))
  pval   <- test$`Pr(>Chisq)`[2]
  result <- if (pval > 0.05) "PASS" else if (pval > 0.01) "MARGINAL" else "FAIL"
  cat(sprintf("%-55s  df=%d  p=%.3f  %s\n", label, length(pre), pval, result))
  invisible(test)
}

pretrend_test(employed_f,        "Employment full (full TIP)")
pretrend_test(employed_p,       "Employment partial (full TIP)")
pretrend_test(earn,          "Log earnings (full TIP)")
pretrend_test(offense,       "Offense (full TIP)")
pretrend_test(employed_f_pre22,    "Employment full (pre-2022 cohort)")
pretrend_test(employed_p_pre22,   "Employment partial (pre-2022 cohort)")
pretrend_test(earn_pre22,      "Log earnings (pre-2022 cohort)")
pretrend_test(offense_pre22,   "Offense (pre-2022 cohort)")
pretrend_test(employed_f_post22,   "Employment full (post-2022 cohort)")
pretrend_test(employed_f_post22,  "Employment partial (post-2022 cohort)")
pretrend_test(earn_post22,     "Log earnings (post-2022 cohort)")
pretrend_test(offense_post22,  "Offense (post-2022 cohort)")
```
```{r}
#Event study plots

#full TIP
iplot(
  offense,
  ref.line = -1,
  xlab = "Relative Year",
  main = "Event Study: Offense (Full TIP)"
)

iplot(
  earn,
  ref.line = -1,
  xlab = "Relative Year",
  main = "Event Study: Earnings Full Year (Full TIP)"
)

iplot(
  employed_f,
  ref.line = -1,
  xlab = "Relative Year",
  main = "Event Study: Employment Full Year (Full TIP)"
)

iplot(
  employed_p,
  ref.line = -1,
  xlab = "Relative Year",
  main = "Event Study: Employment Partial Year (Full TIP)"
)
```
```{r}
#Event study plots- pre22
iplot(
  offense_pre22,
  ref.line = -1,
  xlab = "Relative Year",
  main = "Event Study: Offense (pre-2022 cohort)"
)

iplot(
  earn_pre22,
  ref.line = -1,
  xlab = "Relative Year",
  main = "Event Study: Earnings Full Year (pre-2022 cohort)"
)

iplot(
  employed_f_pre22,
  ref.line = -1,
  xlab = "Relative Year",
  main = "Event Study: Employment Full Year (pre-2022 cohort)"
)

iplot(
  employed_p_pre22,
  ref.line = -1,
  xlab = "Relative Year",
  main = "Event Study: Employment Partial Year (pre-2022 cohort)"
)
```
```{r}
#Event study plots-post 22

iplot(
  offense_post22,
  ref.line = -1,
  xlab = "Relative Year",
  main = "Event Study: Offense (post-2022 cohort)"
)

iplot(
  earn_post22,
  ref.line = -1,
  xlab = "Relative Year",
  main = "Event Study: Earnings Full Year (post-2022 cohort)"
)

iplot(
  employed_f_post22,
  ref.line = -1,
  xlab = "Relative Year",
  main = "Event Study: Employment Full Year (post-2022 cohort)"
)

iplot(
  employed_p_post22,
  ref.line = -1,
  xlab = "Relative Year",
  main = "Event Study: Employment Partial Year (post-2022 cohort)"
)
```
```{r}


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
